### ISSUE TITLE
另一种单臂路由实现方案

### ISSUE THREAD

**Issue by suzukua** [larsonzh/sar#1]
首先感谢大佬的脚本，用起来很稳！👍

目前看到大佬的思路是通过vlan延伸lan到上一级网络！

1，华硕官方固件支持wan指定vlan(eth0.x)，那么在这种情况下可否把wan(eth0)和lan桥接起来向外部延伸呢？这种方案我在openwrt上验证通过，华硕上不太熟悉，还请赐教。
2，此脚本官方固件是否同样适用呢？不适用的话主要是那些原因呢？

**Comment by suzukua** [comment]
> 首先感谢大佬的脚本，用起来很稳！👍
> 
> 目前看到大佬的思路是通过vlan延伸lan到上一级网络！
> 
> 1，华硕官方固件支持wan指定vlan(eth0.x)，那么在这种情况下可否把wan(eth0)和lan桥接起来向外部延伸呢？这种方案我在openwrt上验证通过，华硕上不太熟悉，还请赐教。 2，此脚本官方固件是否同样适用呢？不适用的话主要是那些原因呢？

`
假设指定wan(eth0)的vlan是10(eth0.10)：
brctl addif br0 eth0
`
没测试过。。。。

**Comment by larsonzh** [comment]
方案是在本人现有机型上试出来的，在华硕老款arm平台的梅林固件机器上运行是稳定可靠的，其他机型和固件的情况不太清楚，相关资料也很难找到，只能自己测试和观察，也希望能将结果共同分享。

**Comment by suzukua** [comment]
> 

感谢回复。参考你的脚本，我在AX86U上验证了上面的方式是能够行通的，代码如下：
`
ifconfig eth0 down
`
`
brctl addif br0 eth0
`
`
ifconfig eth0 up
`

我主要的场景是用光猫lan口扩展AX86U的lan，光猫貌似不支持VLAN的lan延伸(也许是我不会玩儿)

**Comment by larsonzh** [comment]
很多光猫不支持或难以支持这种扩展，建议加一个支持vlan的五口交换机，如网件、水星之类的，价格也不贵，就像方案教程里介绍的那样。
